outputPath: c:\temp\Generated project\ChamExtension
templatesPath: C:\source\CodeAutomation\data\templates\ChamExtension
git:
  userName: user
  email: user@mail.com
  branchName: develop
  commitName: Code generation Number 5
script:
  tool: powershell.exe  
  commands:
  - command: dotnet tool install Cake.Tool --version 1.1.0 -g  
    workingFolder: c:\temp\Generated project\ChamExtension
  - command: dotnet restore
    workingFolder: c:\temp\Generated project\ChamExtension\src
  - command: .\build.ps1 --target BuildAndPackageLocal
    workingFolder: c:\temp\Generated project\ChamExtension
dataSource:
  settingsProcessor: default
  dataSourceType: csv
  culture: en-AU
  connectionString: c:\temp\Csv
fileSystem:
  updateableFileMask: '*.gen.*'
  extensions:
  - template: .sbn-cs 
    result: .cs
  - template: .sbn-sln 
    result: .sln
  - template: .sbn-xaml
    result: .xaml
  - template: .sbn-csproj
    result: .csproj
  - template: .sbn-DotSettings
    result: .DotSettings
  - template: .sbn-cake
    result: .cake
  - template: .sbn-props
    result: .props
  - template: .sbn-json
    result: .json
codeModel:
  project:
    customer: Customer
    name: DemoProject